const test = [
  [
    '創社元老',
    'Maggie',
    'BCG',
    'Consultant',
    'WEF Taipei Global Shaper、Morgan Stanley IBD Intern、UBS Investment Bank Summer Analyst、Exchange in University of Helskin, Finland、臺灣大學財務金融學系',
  ],
  [
    '創社元老',
    'Hector',
    '臺灣大學國際企業所',
    'Allianz Group Intern、Bexcel Consultants Intern、Bain & Co. Intern、Exchange in University of Queensland in Australia、中國人民大學數學系',
  ],
  [
    '創社元老、Peggy',
    'Yahoo',
    'Sr. Specialist',
    'Yahoo Sr. Strategy Planner、Nielsen Retailer Services Assistant、浙江大學管理學院交換、臺灣大學國際企業學系',
  ],
  [
    '創社元老',
    'Nelson',
    'MediaTek',
    'Engineer',
    '三篇IEEE國際論文   第一作者、臺灣大學電子所碩士、臺灣大學電機工程學系、臺灣大學財務金融學系',
  ],
  [
    '創社元老',
    'Hank',
    'Google HQ',
    'Software Engineer',
    'Carnegie Mellon University, Master of Computational Data Science、第17屆臺大盃全國橋藝競賽總召、臺灣大學資訊管理研究所碩士、臺灣大學資訊管理學系',
  ],
  [
    '第2屆成員',
    'Claire',
    'P&G',
    'Assistant Brand Manager',
    'Mckinsey & Co. R&I Intern、臺灣大學財務金融學系',
  ],
  [
    '第2屆成員',
    'Michelle',
    'Citi Corporate &',
    'Investment Bank',
    'Analyst',
    'UBS Investment Bank、臺灣大學財務金融學系',
  ],
  [
    '第2屆成員',
    'Paula',
    'Teach for Taiwan',
    'Director of Operations',
    'UBS Intern、KPMG Intern、Columbia University MPA、臺灣大學會計學系',
  ],
  [
    '第2屆成員',
    'Joyce',
    'THLK',
    'Attorney-at-Law',
    'Taiwan Taoyuan District Court Law Clerk、UBS Investment Bank Equity Deriatives PTA、臺灣大學科法所碩士、臺灣大學經濟學系',
  ],
  [
    '第2屆成員',
    'Jenny',
    'PwC Taipei office',
    'Tax consultant',
    'PwC Intern、臺大醫鯊游泳社總務、臺灣大學會計學系',
  ],
  [
    '第2屆成員',
    'Charlie',
    '臺灣大學經濟學系',
    'UBS Investment Bank Equity Reseach Intern、Goldman Sachs summer Intern、Grand Cathay Securities Summer Analyst、Fubon Securities Sales & Trading Winter Intern、Exchange in University of Hong Kong',
  ],
  ['第2屆成員', 'Alistair', 'Asus', 'Oversea Sales', '臺灣大學工商管理學系'],
  [
    '第3屆成員',
    'Cindy',
    'StorySense',
    'Computing Strategist',
    'StorySense Computing Strategist、Pebbo Project Coordinator、SLP (Startup Leadership Program) Taipei Fellow、IBM Mentoring Program、臺灣大學電機工程學系',
  ],
  [
    '第3屆成員',
    'Karen',
    'The Wharton School',
    'MBA candidate',
    'McKinsey & Company Associate、Mckinsey&Co. Intern、HSBC Summer Intern、Tong Shen Enterprise Summer Intern、Exchange in Rotterdam School of Management Erasmus University、臺灣大學國際企業系',
  ],
  [
    '第3屆成員',
    'Haas',
    'Macquarie',
    'Associate Analyst',
    'Athena Capital Management Equity Research Intern、Cathay Life Insurance Investment Accounting Intern、臺大種子教育社公關長、臺灣大學機械工程學系',
  ],
  [
    '第3屆成員',
    'Eric',
    '臺灣大學醫學系',
    'Exchange in University of California, Berkeley、第41屆國際化學奧林匹亞競賽 金牌、第19屆國際生物奧林匹亞競賽 金牌',
  ],
  [
    '第3屆成員',
    'Jean',
    'Wayfair Data Scientist (Forecasting)',
    'UC Berkeley Master in Operations Research、花旗銀行決策管理部門/消金MA、QIC Research Intern、臺大模擬聯合國社學術部、臺灣大學財務金融學系',
  ],
  [
    '第3屆成員',
    'Peter',
    'Corning Manufacturing Strategy Program Manager',
    'DKSH Business Development Specialist、University of Illinois at Urbana-Champaign Technology Management Master、臺灣大學資訊管理學系',
  ],
  [
    '第4屆成員',
    'Candy',
    'University of Minnesota',
    'Bank of Tokyo-Mitsubishi UFJ FX Trader、Bank of Tokyo-Mitsubishi UFJ Global Banker Program、Mitsubishi Tokyo UFJ Bank Global Banker Program、臺灣大學電機工程學系、經濟學系(輔系)',
  ],
  [
    '第4屆成員',
    'Rosalind',
    '余宛如立法委員法案助理',
    'Skymizer Marketing Manager、Tripda Business Development Manager、Shalom!Israel Cofounder、Pebbo Intern Consultant、Exchange in The Hebrew University of Jerusalem, Israel、AIESEC 臺大分會會長、臺灣大學法律學系、政治學系國際關係組(雙主修)、經濟學系(輔系)',
  ],
  [
    '第4屆成員',
    'Andrew',
    '哈佛大學分子細胞生物學博士班',
    '臺灣大學醫學系 、臺灣大學物理學系 、McKinsey & Co. Summer Business Analyst 、The Investigator Taiwan 生物科學研發策進社群 發起人',
  ],
  [
    '第4屆成員',
    'Jason',
    'Teach for Taiwan',
    'Teacher',
    '2013年總統教育獎得主、城市浪人共同創辦人、Gift Citizen Social Enterprise Member、臺大證券研究社社長、臺大不同凡響社學術、臺灣大學農業經濟學系',
  ],
  [
    '第4屆成員',
    'Yvonne',
    'Bank of America',
    'Merrill Lynch',
    'Analyst',
    'Bank of America Merrill Lynch Summer Analyst、Dior luxury marketing Assistant、Standard Chartered Bank Intern、北京大學交換生、臺大企業領袖社社長、臺灣大學財務金融學系',
  ],
  [
    '第4屆成員',
    'Kate',
    'Corning Glass Technology Senior Operations Strategy Project Manager',
    'Corning Glass Technologies Manufacturing Strategy Analyst、Ayers Saint Gross Marketing and B/D Analysis Intern、Amnesty International Project Volunteer、Corning Display Technologies Competitor Intelligence Intern',
  ],
  [
    '第5屆成員',
    'Megan',
    'BCG',
    'Associate',
    'Shopee Senior Associate、OgilvyOne Account Manager、臺灣大學財務金融學系',
  ],
  ['第5屆成員', 'Spenser', '台大醫院', '實習醫生', '臺灣大學醫學系學士'],
  [
    '第5屆成員',
    'Joy',
    'Farcent',
    'Brand Marketing Supervisor',
    'Johnson & Johnson Consumer Supply Chain Specialist、Mercedes-Benz Taiwan Intern、Richi Intern、Exchange in University of Minnesota、臺灣大學工商管理學系',
  ],
  [
    '第5屆成員',
    'Alicia',
    'DKSH',
    'Business Analyst',
    "L'OREAL Taiwan Intern、Exchange in Rotterdam School of Management、臺大亞太青年創業社公關、臺灣大學國際企業學系",
  ],
  [
    '第5屆成員',
    'Wendy',
    'P&G',
    'Senior Brand Manager',
    'Johnson & Johnson Assistant Category Manager、DKSH Business Development Intern、Exchange in SciencesPo Paris、臺灣大學第14屆模擬聯合國社公關、臺灣大學外國語文學系',
  ],
  [
    '第5屆成員',
    'Vincent',
    'Under Armour',
    'E-commerce Manager',
    'Under Armour, Senior Marketing Specialist、Under Armour, Product Planner、TAAZE Online bookstore, Product Manager 、臺大意識報社長、臺灣大學社會學系',
  ],
  [
    '第5屆成員',
    'Melody',
    'Johnson & Johnson',
    'Vision Care Brand Manager',
    "L.E.K. Consulting Intern、L'OREAL Marketing Intern、Dentsu Account Planning Intern、Eland Tech Business Analyst Intern、KPMG PTA、臺灣大學國際企業所碩士、臺灣大學經濟學系",
  ],
  [
    '第6屆成員',
    'Jenny',
    '臺灣大學工商管理學系',
    'Mckinsey & Co. R&I Intern、MeepShop Web Developer、科技部落格 Inside 編輯、Exchange in Australia National University、第六屆 GIS Taiwan 全球集思論壇召部、臺灣大學工商管理學系學士',
  ],
  [
    '第6屆成員',
    'Esther',
    'Harvard Business School MBA candidate',
    'BCG Senior Associate、BCG PTA、Exchange in Universite Montpellier II, France、臺灣大學工商管理學系',
  ],
  [
    '第6屆成員',
    'Jerry',
    'McKinsey & Co',
    'Associate',
    'Apple Regional Supply Demand Planner、Goldman Sachs Equity Research Analyst、Serra Advisors LP Financial Advisory Analyst、UBS Investment Bank Equity Research Intern、State Street Global Markets Intern、Exchange in Temple University, USA、臺灣大學財務金融學系',
  ],
  [
    '第6屆成員',
    'Sherry',
    '臺灣大學財務金融學系',
    'Schneider Electric Business Development Intern、Citi bank Treasury & Trade Solution Intern、HTC Corporation Sales & Marketing Intern、臺灣大學財務金融學系',
  ],
  [
    '第6屆成員',
    'Anita',
    'Nestle Taiwan Trade Marketing Specialist',
    'Geometry Global intern、Mondelez International (Taiwan) Intern、第9屆臺大世界志工社 活動部、臺灣大學國際企業學系',
  ],
  [
    '第6屆成員',
    'Jennifer',
    'Camp Mobile Taiwan Product Specialist',
    'IAMCOMPANY Inc. Taiwan Branch Service Manager、MIC of III Research Associate Intern、Exchange in Yonsei University, Korea、臺大韓國留學生會共同創辦人暨台韓交流部長、臺灣大學國際企業學系',
  ],
  [
    '第6屆成員',
    'Sarah',
    'Twin Oaks Education',
    'Co-founder',
    'Google AI Education, Assistant Manager, Marketing (Temporary Full-Time)、Google Play, Marketing Specialist (Temporary Full-Time)、Exchange in the University of Manchester, UK、奧美互動行銷業務部門實習生、綠藤生機產品開發暨行銷推廣實習生、臺大EMBA校友基金會校友會刊創刊號執行編輯、臺灣大學國際企業學系',
  ],
  [
    '第6屆成員',
    'Celine',
    'APT',
    'Business Consultant',
    'JPMorgan Asset Management Summer Analyst、Gin Ko Asset Management Intern、Exchange in the University of Southern California, Marshall Business School、臺大國企系系學會學術部部長、臺灣大學國際企業學系',
  ],
  [
    '第7屆成員',
    'Allen',
    '臺灣大學商學研究所',
    'Cathay United Bank Human Resource Intern、eLand Tech co. Analyst Intern、INNO4G Venture Capital Summer Intern、VMFive Market Research Intern、政治大學財政學系',
  ],
  [
    '第7屆成員',
    'Angel',
    '臺灣大學經濟學系',
    'AppWorks Finance & Investment Dept. Intern、AIESEC臺大分部副會長',
  ],
  [
    '第7屆成員',
    'Jasmine',
    '臺灣大學醫學系',
    'Academia Sinica Neuroscience Program Intern、Mackay Memorial Hospital Cancer Research Intern、International Genetically Engineered Machine (iGEM) Competition Gold Medal',
  ],
  [
    '第7屆成員',
    'Kevin',
    '、IBM',
    'Business & Strategy Consultant',
    'Quanta Computer Management Associate、DBS Bank Institutional Banking Intern、A.C Nielsen Retail service Intern、Advantech Digital Marketing Intern、資策會產業情報研究所 研究助理、臺大全球集思論壇副召集人、臺大國企系籃球隊隊長、臺灣大學國際企業學系',
  ],
  [
    '第7屆成員',
    'Peter',
    '臺灣大學工商管理學系',
    'Bebit Part-time Assistant、研華科技公司數位行銷實習生、TMI台灣創意工場 實習生、Meaning4 具有社會意義的插畫品牌共同創辦人、臺大亞太青年創業社 社長',
  ],
  [
    '第7屆成員',
    'Stephanie',
    'Harvard Graduate School of Education, Master of Education, Human Development and Psychology',
    'Citibank Corporate Banking Assistant Relationship Manager Associate、臺大模擬聯合國社副社長、臺灣大學工商管理學系學士、UC Berkeley Economics, Bachelors Degree',
  ],
  [
    '第7屆成員',
    'Tiffany',
    'Broadshine Asset Management Research Analyst',
    'Yuanta Investment Consulting Macro Researcher、Yuanta Investment Consulting Equity Research Associate、Emerald Orient Capital Research Intern、臺大美食烹飪社副社長、臺灣大學財務金融學系',
  ],
  [
    '第8屆成員',
    'Aki',
    'Facebook',
    'Technical Infra Program Manager',
    'VMFive Product Manager、臺灣大學哲學系',
  ],
  [
    '第8屆成員',
    'Shuo-Ru',
    'Seaspan Corporation Country Manager, Taiwan',
    'Bank of America Merrill Lynch (Hong Kong) - Corporate and Investment Banking Associate、Bank of America Merrill Lynch (Hong Kong) - Corporate and Investment Banking Analyst、Bank of America Merrill Lynch (Taiwan) - Corporate and Investment Banking Summer Analyst、Honsin Investment Equity Research, Off-Cycle Research Assistant、台灣大學經濟系',
  ],
  [
    '第8屆成員',
    'Anderson',
    '中華開發創投',
    'MA',
    'Air Liquide Industrial Merchant Business Analyst、臺大化工系NTU ChEers 創辦人、臺灣大學材料所碩士、臺灣大學化學工程學系',
  ],
  [
    '第8屆成員',
    'Daniel',
    '臺灣大學商學研究所',
    'P&G HKTW PS INTERN、BCG PTA、Ubag Co-founder、臺灣大學機械工程學系學士',
  ],
  [
    '第8屆成員',
    'Mandy',
    '臺灣大學商學研究所',
    'Gogolook Co., Ltd marketing intern、Tzu-Chi Hospital part-time Research Assistant 、Exchange in Moscow State Linguistic University、臺灣大學心理學系學士',
    '、 ',
  ],
  [
    '第8屆成員',
    'Ray',
    '臺灣大學物理研究所',
    'Taipei Recorder Orchestra、臺灣大學物理學系',
  ],
  [
    '第8屆成員',
    'Tammy',
    'Product Manager',
    'Carnegie Mellon University - MS of Product Management 2019-2020、Propeller Health, Product Manager 、PointClickCare, Intern、ZUZU Hospitality Solutions, Product Manager、Novartis Clinical Research Associate、永齡健康基金會實習生、臺大生技創業學生會 公關、臺大農化系系學會會長、臺灣大學農化所碩士、臺灣大學農化學系',
  ],
  [
    '第9屆成員',
    'David',
    'Harvard Business School',
    'PhD Student in Quantitative Marketing',
    'Migo TV Data Team Lead、APT Business Consultant、InrayTek Data Scientist 、臺灣大學統計碩士、清華大學計量財務金融學系',
  ],
  [
    '第9屆成員',
    'James',
    'Shopee',
    'Frontend Engineer',
    'IF Studio UI/UX & Front-End Intern、Parsons MFADT、臺灣大學化學工程所碩士、臺灣大學化學工程學系',
  ],
  [
    '第9屆成員',
    'Jason',
    'KHL Capital',
    'Private Equity Analyst',
    'Jones Day、M&A Lawyer、MagiCapital Private Equity Intern、Citibank Institutional Banking Intern、臺灣大學財務金融學系、法律學系 (雙主修)',
  ],
  [
    '第9屆成員',
    'Jimmy',
    'J.P. Morgan Equity Research Associate',
    'KGI Securities Equity Research Associate、Natixis CIB Equity Derivatives Sales Trainee、DBS Bank Institutional Banking Intern、Eastspring Investments Summer & Off-Cycle Intern、Exchange in SciencesPo Paris, France、臺灣大學國際企業學系',
  ],
  [
    '第9屆成員',
    'Judy',
    '臺灣大學國際企業學系、哲學系(雙主修)',
    'UPN Company Social Marketing Intern ',
  ],
  [
    '第9屆成員',
    'Jane',
    'HPE, Strategic Procurement Manager',
    'Dell Global Commodity Supply Manager、Quanta Computer Sales Assistant、綠藤生機 數位行銷實習生、台灣大學會計學系',
  ],
  [
    '第10屆成員',
    'Violet',
    'DLE Group',
    'Fund Manager & Investor Relations Lead',
    'London Business School, Masters in Financial Analysis、Bank of America, Investment Banking & Capital Markets Summer Analyst、Morgan Stanley Investment Banking Summer Analyst、Standard Chartered Weath Management Associate',
  ],
  [
    '第10屆成員',
    'Hsin',
    'Master in Management in European School of Technology and Management',
    'Deloitte Germany Financial Advisory Analyst Intern、ADENA Limited Regional Sales Manager 、VoiceTube Executive Editor、臺灣大學法律學系、社會學系（雙主修）',
  ],
  [
    '第10屆成員',
    'William',
    'WOO Network, Strategy & Growth Operation',
    'GoShare Global Expansion、BCG Associate、BCG PTA、IBM Consultant Intern、iCHEF Business Development、研華科技 Market Analyst Intern、臺灣大學國際企業研究所碩士',
  ],
  [
    '第10屆成員',
    'Kate',
    'Infinity Ventures',
    'Analyst',
    'NTU International Business Department 、Exchanges in EBS, Germany、Lakala Payment Co., Ltd Business cooperation Assistant intern、Net Impact Public Relations Manager、Asia-Pacific Student Entrepreneurship Society Vice President',
  ],
  [
    '第10屆成員',
    'Stanley',
    '臺灣大學財務金融學系',
    "Athena Capital Management Equity Research Intern、NTU Vietnam Service Club Leader、Waseda University SILS, Bachelor's Degree",
  ],
  [
    '第11屆成員',
    'Anthony',
    'Senior Data Scientist, Grab',
    'Data Analyst, Garena 、Quantitative Summer Analyst, Indus Capital New York 、National Championship, J.P. Morgan AM Challenge 、M.S., Columbia University 、臺灣大學經濟學系',
  ],
  [
    '第11屆成員',
    'Justin',
    '臺灣大學國際企業學系',
    'aEnrich Digital Technology Corporation Sales Assistant Intern、Teacher Assistant of Mathematic Course in HSNU',
  ],
  [
    '第11屆成員',
    'Xavi',
    'TSMC',
    'Finance Specialist',
    '力旺電子董事長室專案助理、Exchange in Pusan National University, Korea、Integral Analyst Intern、臺灣大學國際企業研究所碩士、清華大學電機系',
  ],
  [
    '第11屆成員',
    'Shao Yen',
    'Meta Account Manager',
    'AWS Business Development Manager、DKSH Business Development Intern、Snapask Business Analytics Assistant、Exchange in The University of California, Irvine、臺灣大學國際企業學系',
  ],
  [
    '第11屆成員',
    'Peter',
    'DBS Bank',
    'Product Manager',
    'DBS Bank,、Management Associate、Standard Chartered Bank, Financial Markets Intern、Yuanta Commercial Bank, Financial Trading Department Intern、臺灣大學國際企業研究所碩士',
  ],
  [
    '第11屆成員',
    'Eric',
    '臺灣大學經濟學研究所',
    'Mastercard Data & Services Intern (Consulting service) 、McKinsey & Co. Scholar 、Acer Business Development Intern 、DKSH Business Development Intern 、臺灣大學經濟學系',
  ],
  [
    '第12屆成員',
    'Lindy',
    'Mastercard',
    'Analyst',
    'DKSH Management Trainee​、beBit Part-time Assistant、Deloitte Audit Intern、National Champion, Deloitte China Tax Competition、Exchange in Rotterdam School of Management、臺灣大學會計學系學士',
  ],
  [
    '第12屆成員',
    'Amy',
    'PicCollage Product Manager',
    'Deloitte Sustainability and Climate Change Consultant、DKSH Business Development Intern、Exchange in Aalto University, Finland、臺灣大學財務金融學系、社會學系(雙主修)',
  ],
  [
    '第12屆成員',
    'Bohr',
    'Corning',
    'Pricing Analyst',
    'Dell Procurement Strategy & PMO Senior Analyst、臺灣大學商學研究所碩士、臺灣大學資訊工程學系',
  ],
  [
    '第12屆成員',
    'Lobelia',
    'Attorney-at-Law',
    'Hubert Hsu and Associates',
    'Miclub Tech. Legal Counsel / Public Relations、Greenvines Branding Intern、PwC Auditing Intern、Exchange in University of Illinois at Urbana-Champaign、臺灣大學法律學系、會計學系(雙主修)',
  ],
  [
    '第12屆成員',
    'Bernie',
    'McKinsey & Company',
    'OrgSolutions Coach',
    'McKinsey & Co. R&I Intern、Shanghai Droi Technology Co. FAE、椰晴小泰陽服務社社長、臺灣大學商學研究所碩士、臺灣大學心理學系',
  ],
  [
    '第12屆成員',
    'Travis',
    'AllianzGI',
    'Global Graduate Trainee',
    'BCG PTA、National Champion, J.P. Morgan Asset Management Challenge、NFAC Chief Managing Director、Nomura Asset Management Fixed Income Research Intern、Nomura Asset Management HR Intern、Asia Value Capital Research Intern、臺灣大學財務金融學系',
  ],
  [
    '第13屆成員',
    'Cathy',
    '臺灣大學財務金融學系、人類學系(輔修)',
    'Cobinhood.Ltd Business Development Team Intern、Mu En Art LLC. Part Time Employee、Global Initiatives Symposium,Student Consultant of Marketing Department、NTU ART Festival Minster of Marketing Department、Finance Department Volleyball Team',
  ],
  [
    '第13屆成員',
    'Charles',
    'Savvy Investment Equity Research Analyst',
    'Schroders Investment Management Intern、Shanghai Commercial & Savings Bank Intern、臺灣大學財務金融學系',
  ],
  [
    '第13屆成員',
    'U.C.',
    'Mastercard D&S Associate Managing Consultant',
    'APT Business Consultant 、臺大假日兒童博物館策展 、APT Business Consultant Intern、BCG Case Team Assistant 、National Champion, J.P. Morgan Asset Mgmt. Challenge 、QIC Research Assistant、元大期貨自營交易實習生、臺大劍道校隊、TutorABC Teacher、臺灣大學財務金融學系',
  ],
  [
    '第13屆成員',
    'Jimmy',
    'Terumo Tokyo HQ, product manager',
    "Hilti Market Research Intern、IBM Summer Intern、H.Specctrum Intern、Exchange in Queen's University, Canada、台大社會創新社副社長、2017 聯合國氣候變遷峰會觀察員 (COP 23)、臺灣大學國際企業學系",
  ],
  [
    '第13屆成員',
    'Corliss',
    'P&G',
    'Senior Brand Manager',
    "HEINEKEN Malaysia Berhad Marketing Executive、National Champion, 2017 Unilever Business Competition、Unilever Customer Marketing Intern、LVMH Watch & Jewelry Marketing Executive、Talee's & Starplace Department Store Marketing Project Specialist、CEMS Master in International Management at HEC Paris & Hong Kong University of Science and Technology、臺灣大學國際企業學研究所",
  ],
  [
    '第13屆成員',
    'Amber',
    'Mazars Consulting (Taiwan) Associate Consultant',
    'Athena Capital Management Equity Research Intern、Galderma Sales & Marketing Intern、Salk Institute Undergraduate Researcher、Academia Sinica Summer Research Intern',
  ],
  [
    '第14屆成員',
    'Anna',
    'Standard Foods Corporation, Assistant Product Manager',
    'HOLA, Management Associate、Teach For Taiwan, Project Intern、Hahow, BD & Project Planning Intern、Exchange in University of Pittsburgh 、NTU Design Thinking Club、臺灣大學國際企業學系',
  ],
  [
    '第14屆成員',
    'Christina',
    'IBM, Industry Consultant',
    'PwC, Senior Consultant、Fortuna Intelligence Co., Ltd Marketing Intern、Business Weekly Journalism Intern、Deloitte Risk Advisory Services Intern、Exchange in EMLYON Business School, France 、臺灣大學會計學系、財務金融學系(雙主修)',
  ],
  [
    '第14屆成員',
    'Joseph',
    'UCLA, PhD in Materials Science & Engineering',
    'Cornell University, MS in Materials Science & Engineering、TSMC R&D Engineer Intern、Deloitte Consultant Intern 、MIT Visiting Student Researcher 、臺大吉他社社長、臺灣大學材料科學暨工程學系、化學系(輔修)',
  ],
  [
    '第14屆成員',
    'Ray',
    '統一企業',
    'Product Manager',
    '臺灣大學食品科技研究所碩士、臺灣大學農業化學系',
  ],
  [
    '第14屆成員',
    'Triny',
    'McKinsey & Co,',
    'Business Analyst',
    'Mastercard Data & Services (APT) Summer Intern、Standard Chartered Bank, IG Intern、Cathay Life Insurance Company, District Director Assistant、臺灣大學財務金融學系',
  ],
  [
    '第15屆成員',
    'Jonas',
    '臺灣大學政治學系',
    'Associate Product Manager, Dcard、Design Thinking Coach, Alphateam、Product Manager, VeryBuy非常勸敗、Rethink Competition 2018 Coach',
  ],
  [
    '第15屆成員',
    'Leona',
    'Shopee',
    'Summer Intern',
    'Customer Experience Intern, Shopee、Critical Thinking & Problem Solving (CTPS) Teaching Assistant、臺灣大學政治學系',
  ],
  [
    '第15屆成員',
    'Daniel',
    'Dell Strategic Business Development Analyst',
    ' McKinsey & Co. Scholar 、YCP Solidiance Business Analyst Intern、GIS Taiwan Director of Marketing and Design、臺灣大學國際企業學系',
  ],
  [
    '第15屆成員',
    'Nady',
    'MediaTek',
    'Engineer',
    'Delta Electronic Electronic Enigeering Intern、NCKU Graduates Association President、NCKU Student Union Public relation team leader、臺灣大學電子所碩士、成功大學資訊工程學系 學士',
  ],
  [
    '第15屆成員',
    'Jason',
    '臺灣大學心理學系',
    '臺灣大學心理學系學士、心理學系系刊《逆光》專案部長',
  ],
  [
    '第16屆成員',
    'Nissen',
    '臺灣大學哲學系',
    'Junyi Academy Software Engineer、Teach for Taiwan Software Engineer、AlphaCamp Teaching Assistant 、《臺大人職場手冊》總編輯 、臺大哲學桂冠獎 首獎',
  ],
  [
    '第16屆成員',
    'Zora',
    'Bytedance Business Analyst',
    'Shopee Business Analyst Intern、Verizon Media (Yahoo) B2C Marketing Intern、只要有人社群顧問 Social Marketing Intern、臺灣大學工商管理學系',
  ],
  [
    '第16屆成員',
    'Jane',
    '臺灣大學財務金融學系',
    'MagiCapital Private Equity Intern、Shin Kong Investment Trust, Global Investment Intern、beBit Consulting Intern、Calls over Ridges Intern',
  ],
  [
    '第16屆成員',
    'Jeffery',
    '臺灣大學應數所碩士',
    'Asia Market Access, Market Research Intern、2nd Price, SAS Data Analysis Competition (EVA Airline)、Cathay Life Insurance, Fintech Research Intern、臺大數學系籃隊長、臺灣大學數學系',
  ],
  [
    '第16屆成員',
    'Jean',
    '臺灣大學心理所碩士',
    'XROUND Digital Marketing Intern、OpenHCI 2019 UX Designer、台北榮民總醫院 臨床實習心理師、台灣積體電路股份有限公司 HR Intern、臺灣大學心理學系',
  ],
  [
    '第17屆成員',
    'Fen',
    'Cherubic Ventures Analyst',
    'McKinsey & Co.、R&I Intern、Shopee Commercial Summer Intern、AppWorks Intern、臺灣大學商學研究所碩士、政治大學國貿系',
  ],
  [
    '第17屆成員',
    'Chris',
    'McKinsey & Co.',
    'DtV Lab ML Solution Intern',
    'AU Optronic Data Science Intern、YEF Program 2018 Delegate、臺灣大學工業工程研究所碩士、交通大學工業工程與管理學系',
  ],
  [
    '第17屆成員',
    'James',
    'Corning Sr. Strategy Analyst',
    'DKSH, Business Development Intern、Strategy Consulting—Approach and Practice (SCAP), Teaching Assistant、beBit, Consultant PTA、Appworks Analyst Intern、臺灣大學商學研究所、清華大學經濟學系',
  ],
  [
    '第17屆成員',
    'Tim',
    'Shopee',
    'Customer Experience Associate',
    'DIT Startup, BA Intern、ECFIT BD Intern、iFit Supply Chain Intern、臺灣大學國際企業學系',
  ],
  [
    '第17屆成員',
    'Adam',
    '、Nan Shan Life Management Associate',
    'Shopee Data Analyst intern、Verite Consulting、International, Intern、天下教育，共同創辦人、臺灣大學商學研究所、中原大學企管系',
  ],
  [
    '第17屆成員',
    'Aidan',
    '臺灣大學資管學系',
    '暨歐盟研究學程',
    'GoShare Product Manager Intern、Microsoft Technical Assistant Intern (Services Team)、Cathay Life Insurance Fintech Engineer Intern、Ernst & Young Management Consultant Intern',
  ],
  [
    '第18屆成員',
    'Yu Ting​',
    '臺灣大學工商管理學系',
    '活水影響力投資 實習生、GAP Inc. Shanghai International Intern、時代基金會 實習生',
  ],
  [
    '第18屆成員',
    'Ethen',
    '臺灣大學臨床藥學士',
    'H.Spectrum Accelerator Intern、TTY Biopharm Company Limited Intern',
  ],
  [
    '第18屆成員',
    'Leo',
    'beBit TECH, Digital Strategy Manager',
    'beBit Consultant、Cathay Financial Holdings, Tech driven team、Nice Clinic Contract-based consultant、COBINHOOD, Operation intern、Exchange in Uppsala University, Sweden、臺灣大學財務金融學系',
  ],
  [
    '第18屆成員',
    'Claire',
    'Master in Financial Analysis London Business School',
    'Alliance Bernstein Multi Asset Product Analyst Intern、Citibank Global Consumer Banking Summer Analyst、YCP Solidiance Business Consulting Intern、The University of Hong Kong Exchange Student、University of California, Berkeley Exchange Student、臺灣大學經濟學系',
  ],
  [
    '第18屆成員',
    'Trevor',
    '臺灣大學藝術史研究所',
    'Private Museum Collection Researcher、Institute for Information Industry－MIC Research Assistant、KKday SEA Digital Marketing Intern、NTPC Yingge Ceramics Museum、Special Exhibition Curating Member、臺灣大學國際企業學系 ',
  ],
  [
    '第18屆成員',
    'Sabrina​',
    'REnato lab',
    'Junior Project Coordinator',
    '台灣大學哲學系',
  ],
  [
    '第19屆成員',
    'ShanYu',
    'WOO Network, Product Manager',
    'beBit, Business Consultant PTA、NEXT BANK, User Experience Researcher intern、Visiting student at Faculty of Humanities at Charles University、臺灣大學心理學系雙社會學系暨婦女與性別研究學程',
  ],
  [
    '第19屆成員',
    'Shannon',
    "L'Oréal, HR Management Trainee",
    'Mercer Taiwan, Career Business Intern、Rayark Game, Intern、Design Thinking Coach、Freelance Illustrator、台灣大學心理學系',
  ],
  [
    '第19屆成員',
    'Laura',
    '臺灣大學會計學系',
    'Garena, Management Associate、beBit, Business Consultant PTA、Standard Chartered Bank, International Graduate Intern-Digital Banking、Deloitte, Audit & Assurance Intern',
  ],
  [
    '第19屆成員',
    'Eric',
    'Insider Business Development Specialist',
    'Shopee, Category Management Intern、JihSun Bank, Treasury Division Intern、180 Degree Consulting Club Taiwan, Director of Business Development、臺灣大學財務金融學系',
  ],
  [
    '第19屆成員',
    'Nora',
    '臺灣大學流預所',
    'Taiwan Burden of Disease Center, Research Assistant、心理學系系刊《逆光》專案部長、臺灣大學心理學系、生物統計學程',
  ],
  [
    '第19屆成員',
    'Vera',
    '臺灣大學財務金融學系',
    'ActiveFence, Product Management Intern Research Assistant、beBit, Business Consultant PTA、Taishin Investment Advisory, Analyst Intern',
  ],
  [
    '第20屆成員',
    'Chris',
    'Analyst Intern at CloudAlpha Capital',
    'MagiCapital Private Equity Analyst Intern、Statement Dog Equity Research Intern、Affairs of Economic of R.O.C Intern、RYS-200 Yoga Instructor NTU & NTNU Literature Awards、臺灣大學哲學系、經濟系（輔修）',
  ],
  [
    '第20屆成員',
    'Paul',
    '、Ambrose, Advisors Analyst',
    'Exchange in Lund University、臺灣大學財務金融學系',
  ],
  [
    '第20屆成員',
    'Sara',
    '臺灣大學商學研究所',
    'Fubon Financial Holdings Product Development Intern、DBS Bank Credit Analyst、Eastspring Investments Fund Accounting Intern、Ernst & Young Audit Intern、臺灣大學會計學系',
  ],
  [
    '第20屆成員',
    'Hannibal',
    '臺灣大學機械工程學系',
    'EmoMask Technology Co-Founder & CEO、Google Hardware Product Sprint Program Student Team Leader、National Taiwan University Racing Team Embedded System Engineer',
  ],
  [
    '第20屆成員',
    'Louis',
    'Statementdog Academy, Business Development Manager',
    'Tang Wealth (Beijing, China) Research Assistant Intern、Cathay United Bank, Digital Application Intern、Exchange in Guanghua School of Management Peking University, China、臺大魔術社社長、臺灣大學財務金融學系、心理學系（雙主修）',
  ],
  [
    '第20屆成員',
    'Amanda',
    'Mercer Consulting Career Business Intern',
    '臺灣大學社會學研究所、臺灣大學社會學系',
  ],
  [
    '第21屆成員',
    'Emily',
    '臺灣大學財務金融所',
    'WOO Network Product Management Intern、Cathay United Bank International Strategic Planning Intern、Deloitte & Touche Financial Industry Risk Consultant Intern',
  ],
  [
    '第21屆成員',
    'Gary',
    'Hotai Motor Lexus Intern',
    'FunNow Growth Intern、Standard Chartered Bank Summer Intern、CTPS Teaching Assistant、臺灣大學國際企業學系',
  ],
  [
    '第21屆成員',
    'Iris',
    'Unilever Marketing Intern',
    'Cathay SITE Summer Intern、Exchange in Yale-NUS, Singapore、臺灣大學國際企業學系',
  ],
  [
    '第21屆成員',
    'Jenny',
    '臺灣大學國際企業學系',
    'Appier Enterprise Solution Sales Intern、25sprout Business Development Intern',
  ],
  [
    '第21屆成員',
    'Jim',
    'Graphen Data Scientist Intern',
    '臺灣大學資訊工程學系',
  ],
];

const member = [
  {
    _id: '63ba25546df1fe239bad9dc6',
    name: 'Maggie',
    number: '1',
    jobTitle: 'BCG Consultant',
    exp: [
      'WEF Taipei Global Shaper',
      'Morgan Stanley IBD Intern',
      'UBS Investment Bank Summer Analyst',
      'Exchange in University of Helskin, Finland',
      '臺灣大學財務金融學系',
    ],
    tags: [''],
    avatar:
      'http://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,h_540,w_720/okc98mob2hz8y2hexckw.jpg',
  },
  {
    _id: '63ba264b84250ef9dd911c47',
    name: 'Hector',
    number: '1',
    jobTitle: '臺灣大學國際企業所',
    exp: [
      'Allianz Group Intern',
      'Bexcel Consultants Intern',
      'Bain & Co. Intern',
      'Exchange in University of Queensland in Australia',
      '中國人民大學數學系',
    ],
    tags: [''],
    avater:
      'https://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,f_auto,h_1440,q_90,w_720/89241/%E8%9E%A2%E5%B9%95%E5%BF%AB%E7%85%A7_2016-09-18_%E4%B8%8A%E5%8D%8812.22.24_glvdyx.png',
  },
  {
    _id: '63ba2704535138923020059d',
    name: 'Peggy',
    number: '1',
    jobTitle: 'Yahoo Sr. Specialist',
    exp: [
      'Yahoo Sr. Strategy Planner',
      'Nielsen Retailer Services Assistant',
      '浙江大學管理學院交換',
      '臺灣大學國際企業學系',
    ],
    tags: [''],
    avater:
      'http://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,h_540,w_720/botvwwsjjhunyqglpqxb.jpg',
  },
  {
    _id: '63ba2843c0d81e5ae383f3b6',
    name: 'Nelson',
    number: '1',
    jobTitle: 'MediaTek Engineer',
    exp: [
      '三篇IEEE國際論文   第一作者',
      '臺灣大學電子所碩士',
      '臺灣大學電機工程學系',
      '臺灣大學財務金融學系',
    ],
    tags: [''],
    avater:
      'http://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,h_540,w_720/yj3t9icxnqctbpiut5sk.jpg',
  },
  {
    _id: '63ba2872de14a097dade7443',
    name: 'Hank',
    number: '1',
    jobTitle: 'Google HQ Software Engineer',
    exp: [
      'Carnegie Mellon University, Master of Computational Data Science',
      '第17屆臺大盃全國橋藝競賽總召',
      '臺灣大學資訊管理研究所碩士',
      '臺灣大學資訊管理學系',
    ],
    tags: [''],
    avater:
      'http://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,h_540,w_720/h5unifqgjcq9s7cxp5cq.jpg',
  },
  {
    _id: '63ba290bd9f4d43d2e8e34eb',
    name: 'Claire',
    number: '2',
    jobTitle: 'P&G Assistant Brand Manager',
    exp: ['Mckinsey & Co. R&I Intern', '臺灣大學財務金融學系'],
    tags: [''],
    avater:
      'https://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,f_auto,h_1440,q_90,w_720/89241/a20814d2-6bd3-4ce9-9018-d83bd3557cb8_ceaoyf.jpg',
  },
  {
    _id: '63ba296ed1fbaa7212925603',
    name: 'Michelle',
    number: '2',
    jobTitle: 'Citi Corporate & Investment Bank Analyst',
    exp: ['UBS Investment Bank', '臺灣大學財務金融學系'],
    tags: [''],
    avater:
      'http://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,h_540,w_720/ldlhcrvjkem0cfuqpnue.jpg',
  },
  {
    _id: '63ba29bdf9b0362d0767290a',
    name: 'Paula',
    number: '2',
    jobTitle: 'Teach for Taiwan Director of Operations',
    exp: [
      'UBS Intern',
      'KPMG Intern',
      'Columbia University MPA',
      '臺灣大學會計學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/476104_249808.jpeg',
  },
  {
    _id: '63ba2a42f3c51ada7dfe383b',
    name: 'Joyce',
    number: '2',
    jobTitle: 'THLK Attorney-at-Law',
    exp: [
      'Taiwan Taoyuan District Court Law Clerk',
      'UBS Investment Bank Equity Deriatives PTA',
      '臺灣大學科法所碩士',
      '臺灣大學經濟學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/476104_249808.jpeg',
  },
  {
    _id: '63ba2a8ba896a547c22050f9',
    name: 'Jenny',
    number: '2',
    jobTitle: 'PwC Taipei office Tax consultant',
    exp: ['PwC Intern', '臺大醫鯊游泳社總務', '臺灣大學會計學系'],
    tags: [''],
    avater:
      'http://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,h_540,w_720/auzrrdfrmmegk6fj5ycb.jpg',
  },
  {
    _id: '63ba2adf1abd87b4d3d6f79c',
    name: 'Charlie',
    number: '2',
    jobTitle: '臺灣大學經濟學系',
    exp: [
      'UBS Investment Bank Equity Reseach Intern',
      'Goldman Sachs summer Intern',
      'Grand Cathay Securities Summer Analyst',
      'Fubon Securities Sales & Trading Winter Intern',
      'Exchange in University of Hong Kong',
    ],
    tags: [''],
    avater:
      'http://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,h_540,w_720/ftvecr53mj5e3infh4eo.jpg',
  },
  {
    _id: '63ba2b29db8ac04e497f96da',
    name: 'Alistair',
    number: '2',
    jobTitle: 'Asus Oversea Sales',
    exp: ['臺灣大學工商管理學系'],
    tags: [''],
    avater:
      'http://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,h_540,w_720/zglpphev6pe9eko6f4pm.jpg',
  },
  {
    _id: '63ba2d9b6b8c6d3674f6374c',
    name: 'Cindy',
    number: '3',
    jobTitle: 'StorySense Computing Strategist',
    exp: [
      'StorySense Computing Strategist',
      'Pebbo Project Coordinator',
      'SLP (Startup Leadership Program) Taipei Fellow',
      'IBM Mentoring Program',
      '臺灣大學電機工程學系',
    ],
    tags: [''],
    avater:
      'http://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,h_540,w_720/kuc76qkjkfbkbemtzt7h.jpg',
  },
  {
    _id: '63ba2e400c61a986a1240bee',
    name: 'Karen',
    number: '3',
    jobTitle: 'The Wharton School MBA candidate',
    exp: [
      'McKinsey & Company Associate',
      'Mckinsey&Co. Intern',
      'HSBC Summer Intern',
      'Tong Shen Enterprise Summer Intern',
      'Exchange in Rotterdam School of Management Erasmus University',
      '臺灣大學國際企業系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/29d7fbf1-2288-44c0-916f-aa1504851900_q9nurc.jpg',
  },
  {
    _id: '63ba2f9563f3a555841304c9',
    name: 'Eric',
    number: '3',
    jobTitle: '臺灣大學醫學系',
    exp: [
      'Exchange in University of California, Berkeley第41屆國際化學奧林匹亞競賽 金牌',
      '第19屆國際生物奧林匹亞競賽 金牌',
    ],
    tags: [''],
    avater:
      'http://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,h_540,w_720/e4yisto2gylgubt7jcdj.jpg',
  },
  {
    _id: '63ba300b4a647081fcfab19d',
    name: 'Jean',
    number: '3',
    jobTitle: 'Wayfair Data Scientist (Forecasting)',
    exp: [
      'UC Berkeley Master in Operations Research',
      '花旗銀行決策管理部門/消金MA',
      'QIC Research Intern',
      '臺大模擬聯合國社學術部',
      '臺灣大學財務金融學系',
    ],
    tags: [''],
    avater:
      'http://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,h_540,w_720/oo7amjvsqfyj9uggz174.jpg',
  },
  {
    _id: '63ba30549a462d6b83f97a66',
    name: 'Peter',
    number: '3',
    jobTitle: 'Corning Manufacturing Strategy Program Manager',
    exp: [
      'DKSH Business Development Specialist',
      'University of Illinois at Urbana-Champaign Technology Management Master',
      '臺灣大學資訊管理學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/389921_265576.png',
  },
  {
    _id: '63ba30be2221f2af90b6f783',
    name: 'Candy',
    number: '4',
    jobTitle: 'University of Minnesota',
    exp: [
      'DBank of Tokyo-Mitsubishi UFJ FX Trader',
      'Bank of Tokyo-Mitsubishi UFJ Global Banker Program',
      'Mitsubishi Tokyo UFJ Bank Global Banker Program',
      '臺灣大學電機工程學系、經濟學系(輔系)',
    ],
    tags: [''],
    avater:
      'http://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,h_540,w_720/ob0casr72lrfmlejv8sf.jpg',
  },
  {
    _id: '63ba31238d7e51a1209ee365',
    name: 'Rosalind',
    number: '4',
    jobTitle: '余宛如立法委員法案助理',
    exp: [
      'Skymizer Marketing Manager',
      'Tripda Business Development Manager',
      'Shalom!Israel Cofounder',
      'Pebbo Intern Consultant',
      'Exchange in The Hebrew University of Jerusalem, Israel',
      'AIESEC 臺大分會會長',
      '臺灣大學法律學系、政治學系國際關係組(雙主修)、經濟學系(輔系)',
    ],
    tags: [''],
    avater:
      'http://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,h_540,w_720/ullodldv6agydtpsllgf.jpg',
  },
  {
    _id: '63ba318790f5b8681e77ddd5',
    name: 'Andrew',
    number: '4',
    jobTitle: '哈佛大學分子細胞生物學博士班',
    exp: [
      '臺灣大學醫學系',
      '臺灣大學物理學系',
      'McKinsey & Co. Summer Business Analyst',
      'The Investigator Taiwan 生物科學研發策進社群 發起人',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/4ae3b88c-4840-4be7-bf5d-f0419a07e534_culi3j.jpg',
  },
  {
    _id: '63ba31e8bff780ec560ae9d2',
    name: 'Jason',
    number: '4',
    jobTitle: 'Teach for Taiwan Teacher',
    exp: [
      '2013年總統教育獎得主',
      '城市浪人共同創辦人',
      'Gift Citizen Social Enterprise Member',
      '臺大證券研究社社長',
      '臺大不同凡響社學術',
      '臺灣大學農業經濟學系',
    ],
    tags: [''],
    avater:
      'http://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,h_540,w_720/cc6rydlidfyomgpge7gj.png',
  },
  {
    _id: '63ba323af36be67efa9704a3',
    name: 'Yvonne',
    number: '4',
    jobTitle: 'Bank of America Merrill Lynch Analyst',
    exp: [
      'Bank of America Merrill Lynch Summer Analyst',
      'Dior luxury marketing Assistant',
      'Standard Chartered Bank Intern',
      '北京大學交換生',
      '臺大企業領袖社社長',
      '臺灣大學財務金融學系',
    ],
    tags: [''],
    avater:
      'http://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,h_540,w_720/oyduvjfygrt4uiovyyka.jpg',
  },
  {
    _id: '63ba327da89d865cc387fe57',
    name: 'Kate',
    number: '4',
    jobTitle:
      'Corning Glass Technology Senior Operations Strategy Project Manager',
    exp: [
      'Corning Glass Technologies Manufacturing Strategy AnalystAyers Saint Gross Marketing and B/D Analysis Intern',
      'Amnesty International Project Volunteer',
      'Corning Display Technologies Competitor Intelligence Intern',
    ],
    tags: [''],
    avater:
      'http://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,h_540,w_720/hdjsylkn7oknswhtbsoq.jpg',
  },
  {
    _id: '63ba3332d255903756ead5d7',
    name: 'Haas',
    number: '3',
    jobTitle: 'Macquarie Associate Analyst',
    exp: [
      'Athena Capital Management Equity Research Intern',
      'Cathay Life Insurance Investment Accounting Intern',
      '臺大種子教育社公關長',
      '臺灣大學機械工程學系',
    ],
    tags: [''],
    avater:
      'http://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,h_540,w_720/uy5zcfhlmvyxitbabcsr.jpg',
  },
  {
    _id: '63ba33c79ba60f228b8928ac',
    name: 'Megan',
    number: '5',
    jobTitle: 'BCG Associate',
    exp: [
      'Shopee Senior Associate',
      'OgilvyOne Account Manager',
      '臺灣大學財務金融學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/688574_767877.jpeg',
  },
  {
    _id: '63ba33f41b8799caf0c00b10',
    name: 'Spenser',
    number: '5',
    jobTitle: '台大醫院 實習醫生',
    exp: ['臺灣大學醫學系學士'],
    tags: [''],
    avater:
      'http://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,h_540,w_720/ygl2d6w90dxxfktpqnsc.jpg',
  },
  {
    _id: '63ba343e800e7bb5c13b9333',
    name: 'Joy',
    number: '5',
    jobTitle: 'Farcent Brand Marketing Supervisor',
    exp: [
      'Johnson & Johnson Consumer Supply Chain Specialist',
      'Mercedes-Benz Taiwan Intern',
      'Richi Intern',
      'Exchange in University of Minnesota',
      '臺灣大學工商管理學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/IMG_0006_bxthwa.jpg',
  },
  {
    _id: '63ba347cdd9e25b98bbf197e',
    name: 'Alicia',
    number: '5',
    jobTitle: 'DKSH Business Analyst',
    exp: [
      "L'OREAL Taiwan Intern",
      'Exchange in Rotterdam School of Management',
      '臺大亞太青年創業社公關',
      '臺灣大學國際企業學系',
    ],
    tags: [''],
    avater:
      'https://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,f_auto,h_1440,q_90,w_720/89241/d7211b5f-6450-410b-9b4c-35f15230fa96_lg0qan.jpg',
  },
  {
    _id: '63ba34b7d90dcfabdd15cd97',
    name: 'Wendy',
    number: '5',
    jobTitle: 'P&G Senior Brand Manager',
    exp: [
      'Johnson & Johnson Assistant Category Manager',
      'DKSH Business Development Intern',
      'Exchange in SciencesPo Paris',
      '臺灣大學第14屆模擬聯合國社公關',
      '臺灣大學外國語文學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/IMG_1930_wduaal.jpg',
  },
  {
    _id: '63ba34f6168197e91b2434ff',
    name: 'Vincent',
    number: '5',
    jobTitle: 'Under Armour E-commerce Manager',
    exp: [
      'Under Armour, Senior Marketing Specialist',
      'Under Armour, Product Planner',
      'TAAZE Online bookstore, Product Manager',
      '臺大意識報社長',
      '臺灣大學社會學系',
    ],
    tags: [''],
    avater:
      'http://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,h_540,w_720/npperrxpvkttls7pfsmj.jpg',
  },
  {
    _id: '63ba353f1a5be729ee8f644b',
    name: 'Melody',
    number: '5',
    jobTitle: 'Johnson & Johnson Vision Care Brand Manager',
    exp: [
      'L.E.K. Consulting Intern',
      "L'OREAL Marketing Intern",
      'Dentsu Account Planning Intern',
      'Eland Tech Business Analyst Intern',
      'KPMG PTA',
      '臺灣大學國際企業所碩士',
      '臺灣大學經濟學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/562523_335676.png',
  },
  {
    _id: '63ba35c9d3aa2e0902506c0c',
    name: 'Jenny',
    number: '6',
    jobTitle: '臺灣大學工商管理學系',
    exp: [
      'Mckinsey & Co. R&I Intern',
      'MeepShop Web Developer',
      '科技部落格 Inside 編輯',
      'Exchange in Australia National University',
      '第六屆 GIS Taiwan 全球集思論壇召部',
      '臺灣大學工商管理學系學士',
    ],
    tags: [''],
    avater:
      'http://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,h_540,w_720/jhghnttbwxgts6saeewu.jpg',
  },
  {
    _id: '63ba3600f459a32b3ae3930a',
    name: 'Esther',
    number: '6',
    jobTitle: 'Harvard Business School MBA candidate',
    exp: [
      'BCG Senior Associate',
      'BCG PTA',
      'Exchange in Universite Montpellier II, France',
      '臺灣大學工商管理學系',
    ],
    tags: [''],
    avater:
      'http://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,h_540,w_720/f0avxqj13gv7cmwm2pwo.jpg',
  },
  {
    _id: '63ba364a3242b2166a7552a0',
    name: 'Jerry',
    number: '6',
    jobTitle: 'McKinsey & Co Associate',
    exp: [
      'Apple Regional Supply Demand Planner',
      'Goldman Sachs Equity Research Analyst',
      'Serra Advisors LP Financial Advisory Analyst',
      'UBS Investment Bank Equity Research Intern',
      'State Street Global Markets Intern',
      'Exchange in Temple University, USA',
      '臺灣大學財務金融學系',
    ],
    tags: [''],
    avater:
      'http://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,h_540,w_720/w0zppwjhuyjpv4w6sz87.jpg',
  },
  {
    _id: '63ba36896f890240687ece14',
    name: 'Sherry',
    number: '6',
    jobTitle: '臺灣大學財務金融學系',
    exp: [
      'Schneider Electric Business Development Intern',
      'Citi bank Treasury & Trade Solution Intern',
      'HTC Corporation Sales & Marketing Intern',
      '臺灣大學財務金融學系',
    ],
    tags: [''],
    avater:
      'http://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,h_540,w_720/hzwiqng9kwiwzyhqwf2x.jpg',
  },
  {
    _id: '63ba36c6a683c1259ae352b4',
    name: 'Anita',
    number: '6',
    jobTitle: 'Nestle Taiwan Trade Marketing Specialist',
    exp: [
      'Geometry Global intern',
      'Mondelez International (Taiwan) Intern',
      '第9屆臺大世界志工社 活動部',
      '臺灣大學國際企業學系',
    ],
    tags: [''],
    avater:
      'https://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,f_auto,h_1440,q_90,w_720/89241/23d044d5-0d5c-4268-bec6-89d9f57bf2e0_chggno.jpg',
  },
  {
    _id: '63ba370a32c3359a1fe424fc',
    name: 'Jennifer',
    number: '6',
    jobTitle: 'Camp Mobile Taiwan Product Specialist',
    exp: [
      'IAMCOMPANY Inc. Taiwan Branch Service Manager',
      'MIC of III Research Associate Intern',
      'Exchange in Yonsei University, Korea',
      '臺大韓國留學生會共同創辦人暨台韓交流部長',
      '臺灣大學國際企業學系',
    ],
    tags: [''],
    avater:
      'https://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,f_auto,h_540,q_80,w_720/89241/http_s3.amazonaws.com_feather-files-aviary-prod-us-east-1_f5da8ea5e_2015-02-01_eeef68dd0f92412ba4977914ca729cf2_qpeyaa.jpg',
  },
  {
    _id: '63ba3763b0fb31146a0ae481',
    name: 'Sarah',
    number: '6',
    jobTitle: 'Twin Oaks Education Co-founder',
    exp: [
      'Google AI Education, Assistant Manager, Marketing (Temporary Full-Time)Google Play, Marketing Specialist (Temporary Full-Time)',
      'Exchange in the University of Manchester, UK',
      '奧美互動行銷業務部門實習生',
      '綠藤生機產品開發暨行銷推廣實習生',
      '臺大EMBA校友基金會校友會刊創刊號執行編輯',
      '臺灣大學國際企業學系',
    ],
    tags: [''],
    avater:
      'http://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,h_540,w_720/a3j9wgn63tddtfitpubs.jpg',
  },
  {
    _id: '63ba37a789c773f02581dc4e',
    name: 'Celine',
    number: '6',
    jobTitle: 'APT Business Consultant',
    exp: [
      'JPMorgan Asset Management Summer Analyst',
      'Gin Ko Asset Management Intern',
      'Exchange in the University of Southern California, Marshall Business School',
      '臺大國企系系學會學術部部長',
      '臺灣大學國際企業學系',
    ],
    tags: [''],
    avater:
      'http://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,h_540,w_720/pxtqj3lf9p63x2m6batu.jpg',
  },
  {
    _id: '63ba5471cfe48c56460af06a',
    name: 'Allen',
    number: '7',
    jobTitle: '臺灣大學商學研究所',
    exp: [
      'Cathay United Bank Human Resource Intern',
      'eLand Tech co. Analyst Intern',
      'INNO4G Venture Capital Summer Intern',
      'VMFive Market Research Intern',
      '政治大學財政學系',
    ],
    tags: [''],
    avater:
      'https://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,f_auto,h_540,q_80,w_720/89241/http_s3.amazonaws.com_feather-files-aviary-prod-us-east-1_f5da8ea5e_2015-01-30_3f4d3b07babe4f6ca49ee61736d098a1_ztaem4.jpg',
  },
  {
    _id: '63ba54cdc955365e35031cc9',
    name: 'Angel',
    number: '7',
    jobTitle: '臺灣大學經濟學系',
    exp: ['AppWorks Finance & Investment Dept. Intern', 'AIESEC臺大分部副會長'],
    tags: [''],
    avater:
      'https://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,f_auto,h_540,q_80,w_720/89241/http_s3.amazonaws.com_feather-files-aviary-prod-us-east-1_f5da8ea5e_2015-01-31_84843783b2544868b696bc35ff26be18_by28do.png',
  },
  {
    _id: '63ba55b076e1e26445619d78',
    name: 'Jasmine',
    number: '7',
    jobTitle: '臺灣大學醫學系',
    exp: [
      'Academia Sinica Neuroscience Program Intern',
      'Mackay Memorial Hospital Cancer Research Intern',
      'International Genetically Engineered Machine (iGEM) Competition Gold Medal',
    ],
    tags: [''],
    avater:
      'https://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,f_auto,h_540,q_80,w_720/89241/http_s3.amazonaws.com_feather-files-aviary-prod-us-east-1_f5da8ea5e_2015-01-30_8e7652da114e44f9835ed565b0bc5dc8_s2dh89.jpg',
  },
  {
    _id: '63ba5d028af8d36c8d0591bc',
    name: 'Kevin',
    number: '7',
    jobTitle: 'IBM Business & Strategy Consultant',
    exp: [
      'Quanta Computer Management Associate',
      'DBS Bank Institutional Banking Intern',
      'A.C Nielsen Retail service Intern',
      'Advantech Digital Marketing Intern',
      '資策會產業情報研究所 研究助理',
      '臺大全球集思論壇副召集人',
      '臺大國企系籃球隊隊長',
      '臺灣大學國際企業學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/2018_%E5%B9%B4_06_%E6%9C%88_23_%E6%97%A50002%E5%AE%8C%E6%88%90%E8%83%8C%E6%99%AF%E8%AA%BF%E6%95%B4_ru3uvc.jpg',
  },
  {
    _id: '63ba5d447ce6e7c634048041',
    name: 'Peter',
    number: '7',
    jobTitle: '臺灣大學工商管理學系',
    exp: [
      'Bebit Part-time Assistant',
      '研華科技公司數位行銷實習生',
      'TMI台灣創意工場 實習生',
      'Meaning4 具有社會意義的插畫品牌共同創辦人',
      '臺大亞太青年創業社 社長',
    ],
    tags: [''],
    avater:
      'https://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,f_auto,h_540,q_80,w_720/89241/http_s3.amazonaws.com_feather-files-aviary-prod-us-east-1_f5da8ea5e_2015-02-01_7d70cd561b794087925cf727571276c0_ammhit.jpg',
  },
  {
    _id: '63ba5d80199b69bde1529d78',
    name: 'Stephanie',
    number: '7',
    jobTitle:
      'Harvard Graduate School of Education, Master of Education, Human Development and Psychology',
    exp: [
      'BCitibank Corporate Banking Assistant Relationship Manager Associate',
      '臺大模擬聯合國社副社長',
      '臺灣大學工商管理學系學士',
      'UC Berkeley Economics, Bachelors Degree',
    ],
    tags: [''],
    avater:
      'https://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,f_auto,h_540,q_80,w_720/89241/http_s3.amazonaws.com_feather-files-aviary-prod-us-east-1_f5da8ea5e_2015-02-01_60c89c380169449db3b3f01e5f0f0143_ytggst.jpg',
  },
  {
    _id: '63ba5dcee834a4b5c8185b32',
    name: 'Tiffany',
    number: '7',
    jobTitle: 'Broadshine Asset Management Research Analyst',
    exp: [
      'Yuanta Investment Consulting Macro Researcher',
      'Yuanta Investment Consulting Equity Research Associate',
      'Emerald Orient Capital Research Intern',
      '臺大美食烹飪社副社長',
      '臺灣大學財務金融學系',
    ],
    tags: [''],
    avater:
      'https://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,f_auto,h_540,q_80,w_720/89241/http_s3.amazonaws.com_feather-files-aviary-prod-us-east-1_f5da8ea5e_2015-01-30_77c5c64da1fe4926b66651c84a863781_wthjx3.jpg',
  },
  {
    _id: '63ba5e4cdb9ea3509087e768',
    name: 'Aki',
    number: '8',
    jobTitle: 'Facebook Technical Infra Program Manager',
    exp: ['VMFive Product Manager', '臺灣大學哲學系'],
    tags: [''],
    avater:
      'https://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,f_auto,h_1440,q_90,w_720/89241/85f40aa46fdc48f9895009c2833430d6_pnaorl.jpg',
  },
  {
    _id: '63ba5f2f0ad97ddfd515d8b8',
    name: 'Shuo-Ru',
    number: '8',
    jobTitle: 'Seaspan Corporation Country Manager, Taiwan',
    exp: [
      'Bank of America Merrill Lynch (Hong Kong) - Corporate and Investment Banking Associate',
      'Bank of America Merrill Lynch (Hong Kong) - Corporate and Investment Banking Analyst',
      'Bank of America Merrill Lynch (Taiwan) - Corporate and Investment Banking Summer Analyst',
      'Honsin Investment Equity Research, Off-Cycle Research Assistant',
      '台灣大學經濟系',
    ],
    tags: [''],
    avater:
      'https://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,f_auto,h_1440,q_90,w_720/89241/f990507b-29fc-4ade-a446-6daaf3c00b5d_y0asjq.jpg',
  },
  {
    _id: '63ba5fe0cfc58330f2f52798',
    name: 'Anderson',
    number: '8',
    jobTitle: '中華開發創投 MA',
    exp: [
      'Air Liquide Industrial Merchant Business Analyst',
      '臺大化工系NTU ChEers 創辦人',
      '臺灣大學材料所碩士',
      '臺灣大學化學工程學系',
    ],
    tags: [''],
    avater:
      'https://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,f_auto,h_1440,q_90,w_720/89241/4424e539c3624984a98711bfa4c5f50a_bv6ae9.jpg',
  },
  {
    _id: '63ba60222c17e91102b89bb1',
    name: 'Daniel',
    number: '8',
    jobTitle: '臺灣大學商學研究所',
    exp: [
      'P&G HKTW PS INTERN',
      'BCG PTA',
      'Ubag Co-founder',
      '臺灣大學機械工程學系學士',
    ],
    tags: [''],
    avater:
      'https://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,f_auto,h_1440,q_90,w_720/89241/1049238_651683154842968_1389826888_o_j8vvwu.jpg',
  },
  {
    _id: '63ba606387d6ab206d69a6a9',
    name: 'Mandy',
    number: '8',
    jobTitle: '臺灣大學商學研究所',
    exp: [
      'Gogolook Co., Ltd marketing intern',
      'Tzu-Chi Hospital part-time Research Assistant',
      'Exchange in Moscow State Linguistic University',
      '臺灣大學心理學系學士',
    ],
    tags: [''],
    avater:
      'https://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,f_auto,h_1440,q_90,w_720/89241/42d6632ff39a4875af49e21e753760ba_pv8dzu.jpg',
  },
  {
    _id: '63ba60a39d34c1c257dba7d9',
    name: 'Ray',
    number: '8',
    jobTitle: '臺灣大學物理研究所',
    exp: ['GTaipei Recorder Orchestra', '臺灣大學物理學系'],
    tags: [''],
    avater:
      'https://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,f_auto,h_1440,q_90,w_720/89241/4da4301fce49427f9e176ce9572565dc_z5fz4h.jpg',
  },
  {
    _id: '63ba60ffda54567ff4c1e066',
    name: 'Tammy',
    number: '8',
    jobTitle: 'Product Manager',
    exp: [
      'Carnegie Mellon University - MS of Product Management 2019-2020',
      'Propeller Health, Product Manager',
      'PointClickCare, Intern',
      'ZUZU Hospitality Solutions, Product Manager',
      'Novartis Clinical Research Associate',
      '永齡健康基金會實習生',
      '臺大生技創業學生會 公關',
      '臺大農化系系學會會長',
      '臺灣大學農化所碩士',
      '臺灣大學農化學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/628172_152633.png',
  },
  {
    _id: '63baa6bb858907638607bfc4',
    name: 'David',
    number: '9',
    jobTitle: 'Harvard Business School PhD Student in Quantitative Marketing',
    exp: [
      'Migo TV Data Team Lead',
      'APT Business Consultant',
      'InrayTek Data Scientist',
      '臺灣大學統計碩士',
      '清華大學計量財務金融學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/272802_82155.png',
  },
  {
    _id: '63baa6fd0268226b4897c77d',
    name: 'James',
    number: '9',
    jobTitle: 'Shopee Frontend Engineer',
    exp: [
      'IF Studio UI/UX & Front-End Intern',
      'Parsons MFADT',
      '臺灣大學化學工程所碩士',
      '臺灣大學化學工程學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/9th_James_cn0bfd.jpg',
  },
  {
    _id: '63baa7439322c995aa17c965',
    name: 'Jason',
    number: '9',
    jobTitle: 'KHL Capital Private Equity Analyst',
    exp: [
      'Jones Day M&A Lawyer',
      'MagiCapital Private Equity Intern',
      'Citibank Institutional Banking Intern',
      '臺灣大學財務金融學系、法律學系 (雙主修)',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/723597_529573.png',
  },
  {
    _id: '63baa77dbf658da75e836813',
    name: 'Jimmy',
    number: '9',
    jobTitle: 'J.P. Morgan Equity Research Associate',
    exp: [
      'KGI Securities Equity Research Associate',
      'Natixis CIB Equity Derivatives Sales Trainee',
      'DBS Bank Institutional Banking Intern',
      'Eastspring Investments Summer & Off-Cycle Intern',
      'Exchange in SciencesPo Paris, France',
      '臺灣大學國際企業學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/224782_478983.jpeg',
  },
  {
    _id: '63baa7a6aef25589920926f2',
    name: 'Judy',
    number: '9',
    jobTitle: '臺灣大學國際企業學系、哲學系(雙主修)',
    exp: ['UPN Company Social Marketing Intern'],
    tags: [''],
    avater:
      'https://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,f_auto,h_1440,q_90,w_720/89241/33c29c8225054ec3b9198b49fc27e81f_cwb33k.jpg',
  },
  {
    _id: '63baa7d6ccd8eadb98ba917c',
    name: 'Jane',
    number: '9',
    jobTitle: 'HPE, Strategic Procurement Manager',
    exp: [
      'Dell Global Commodity Supply Manager',
      'Quanta Computer Sales Assistant',
      '綠藤生機 數位行銷實習生',
      '台灣大學會計學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/658338_187266.jpeg',
  },
  {
    _id: '63baa853eec0616a8da0c451',
    name: 'Violet',
    number: '10',
    jobTitle: 'DLE Group Fund Manager & Investor Relations Lead',
    exp: [
      'London Business School, Masters in Financial Analysis',
      'Bank of America, Investment Banking & Capital Markets Summer Analyst',
      'Morgan Stanley Investment Banking Summer Analyst',
      'Standard Chartered Weath Management Associate',
    ],
    tags: [''],
    avater:
      'https://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,f_auto,h_1440,q_90,w_720/89241/fc4ff363-df2b-4748-bbb7-ffe16692e3b4_cgvzsb.png',
  },
  {
    _id: '63baa89b588a82fe9fc30320',
    name: 'Hsin',
    number: '10',
    jobTitle:
      'Master in Management in European School of Technology and Management',
    exp: [
      'Deloitte Germany Financial Advisory Analyst Intern',
      'ADENA Limited Regional Sales Manager',
      'VoiceTube Executive Editor',
      '臺灣大學法律學系、社會學系（雙主修）',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/54435286_1968702046573378_8504678666540679168_n_shxbdy.jpg',
  },
  {
    _id: '63baa8da57701169695b4435',
    name: 'William',
    number: '10',
    jobTitle: 'WOO Network, Strategy & Growth Operation',
    exp: [
      'GoShare Global Expansion',
      'BCG Associate',
      'BCG PTA',
      'IBM Consultant Intern',
      'iCHEF Business Development',
      '研華科技 Market Analyst Intern',
      '臺灣大學國際企業研究所碩士',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/320506_848456.png',
  },
  {
    _id: '63baa919b63ff015562addfb',
    name: 'Kate',
    number: '10',
    jobTitle: 'Infinity Ventures Analyst',
    exp: [
      'NTU International Business Department',
      'Exchanges in EBS, Germany',
      'Lakala Payment Co., Ltd Business cooperation Assistant intern',
      'Net Impact Public Relations Manager',
      'Asia-Pacific Student Entrepreneurship Society Vice President',
    ],
    tags: [''],
    avater:
      'https://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,f_auto,h_1440,q_90,w_720/89241/7a1833f8-446e-4bbb-8174-98209c624498_zdi4fh.jpg',
  },
  {
    _id: '63baa949b4800823fe191f91',
    name: 'Stanley',
    number: '10',
    jobTitle: '臺灣大學財務金融學系',
    exp: [
      'Athena Capital Management Equity Research Intern',
      'NTU Vietnam Service Club Leader',
      "Waseda University SILS, Bachelor's Degree",
    ],
    tags: [''],
    avater:
      'https://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,f_auto,h_1440,q_90,w_720/89241/c0565c77-7b39-49c6-8890-b7572956c189_ydk6zj.jpg',
  },
  {
    _id: '63baabf3989581c475c4052c',
    name: 'Anthony',
    number: '11',
    jobTitle: 'Senior Data Scientist, Grab',
    exp: [
      'Data Analyst, Garena',
      'Quantitative Summer Analyst, Indus Capital New York',
      'National Championship, J.P. Morgan AM Challenge',
      'M.S., Columbia University',
      '臺灣大學經濟學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/mmexport1487017088143_fqh7qz.jpg',
  },
  {
    _id: '63bab18685ee2aa3ff47e3c7',
    name: 'Justin',
    number: '11',
    jobTitle: '臺灣大學國際企業學系',
    exp: [
      'aEnrich Digital Technology Corporation Sales Assistant Intern',
      'Teacher Assistant of Mathematic Course in HSNU',
      '臺灣大學經濟學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/16707408_1229502087127953_4395203925505549091_o_xur9k0.jpg',
  },
  {
    _id: '63bab1cb36d14010b8b6f5f9',
    name: 'Xavi',
    number: '11',
    jobTitle: 'TSMC Finance Specialist',
    exp: [
      '力旺電子董事長室專案助理',
      'Exchange in Pusan National University, Korea',
      'Integral Analyst Intern',
      '臺灣大學國際企業研究所碩士',
      '清華大學電機系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/20180415_%EC%86%A1%EB%8F%84_180919_0022_jwnkkk.jpg',
  },
  {
    _id: '63bab20bc33c33dc0f855ef6',
    name: 'Shao Yen',
    number: '11',
    jobTitle: 'Meta Account Manager',
    exp: [
      'AWS Business Development Manager',
      'DKSH Business Development Intern',
      'Snapask Business Analytics Assistant',
      'Exchange in The University of California, Irvine',
      '臺灣大學國際企業學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/16665360_1229502077127954_6118611454380909446_o_gy7opr.jpg',
  },
  {
    _id: '63bab2a1c336f08675357279',
    name: 'Peter',
    number: '11',
    jobTitle: 'DBS Bank Product Manager',
    exp: [
      'DBS Bank',
      'Management Associate',
      'Standard Chartered Bank, Financial Markets Intern',
      'Yuanta Commercial Bank, Financial Trading Department Intern',
      '臺灣大學國際企業研究所碩士',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/16716300_1229502060461289_2185360210793420911_o_whvcj7.jpg',
  },
  {
    _id: '63bab2e15be7e1a43a9d0b2d',
    name: 'Eric',
    number: '11',
    jobTitle: '臺灣大學經濟學研究所',
    exp: [
      'Mastercard Data & Services Intern (Consulting service)',
      'McKinsey & Co. Scholar',
      'Acer Business Development Intern',
      'DKSH Business Development Intern',
      '臺灣大學經濟學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/bp%E5%A4%A7%E9%A0%AD%E8%B2%BC_lxrwlp.jpg',
  },
  {
    _id: '63bab5bd324c9b8b5f12e887',
    name: 'Lindy',
    number: '12',
    jobTitle: 'Mastercard Analyst',
    exp: [
      'DKSH Management Trainee​',
      'beBit Part-time Assistant',
      'Deloitte Audit Intern',
      'National Champion, Deloitte China Tax Competition',
      'Exchange in Rotterdam School of Management',
      '臺灣大學會計學系學士',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/5fc65fc5-8652-4306-9da8-370932c17a01_nhtjr2.jpg',
  },
  {
    _id: '63bab5f1ab6a8522e884b460',
    name: 'Amy',
    number: '12',
    jobTitle: 'PicCollage Product Manager',
    exp: [
      'Deloitte Sustainability and Climate Change Consultant',
      'DKSH Business Development Intern',
      'Exchange in Aalto University, Finland',
      '臺灣大學財務金融學系、社會學系(雙主修)',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/7571dd8e-fd67-4a11-8536-9a357681dc28_tuc5cm.jpg',
  },
  {
    _id: '63bab6256bd06bd43126d753',
    name: 'Bohr',
    number: '12',
    jobTitle: 'Corning Pricing Analyst',
    exp: [
      'Dell Procurement Strategy & PMO Senior Analyst',
      '臺灣大學商學研究所碩士',
      '臺灣大學資訊工程學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/468898_378742.png',
  },
  {
    _id: '63bab65896e89eaa6a267d1c',
    name: 'Lobelia',
    number: '12',
    jobTitle: 'Attorney-at-Law Hubert Hsu and Associates',
    exp: [
      'Miclub Tech. Legal Counsel / Public Relations',
      'Greenvines Branding Intern',
      'PwC Auditing Intern',
      'Exchange in University of Illinois at Urbana-Champaign',
      '臺灣大學法律學系、會計學系(雙主修)',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/aab8b71e-17d2-496a-9a83-31acad106180_qd1b0j.jpg',
  },
  {
    _id: '63bab698a9cbce012f7fc830',
    name: 'Bernie',
    number: '12',
    jobTitle: 'McKinsey & Company OrgSolutions Coach',
    exp: [
      'McKinsey & Co. R&I Intern',
      'Shanghai Droi Technology Co. FAE',
      '椰晴小泰陽服務社社長',
      '臺灣大學商學研究所碩士',
      '臺灣大學心理學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/bc98dc4a-59ac-4a91-a916-64be8abcf04e_a9irla.jpg',
  },
  {
    _id: '63bab6dde4c90e48a7334193',
    name: 'Travis',
    number: '12',
    jobTitle: 'AllianzGI Global Graduate Trainee',
    exp: [
      'BCG PTA',
      'National Champion, J.P. Morgan Asset Management Challenge',
      'NFAC Chief Managing Director',
      'Nomura Asset Management Fixed Income Research Intern',
      'Nomura Asset Management HR Intern',
      'Asia Value Capital Research Intern',
      '臺灣大學財務金融學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/0fb0f4f9-18f4-4d48-a801-baca1a83d40b_uokha9.jpg',
  },
  {
    _id: '63bab81d319d8da46f76756f',
    name: 'Cathy',
    number: '13',
    jobTitle: '臺灣大學財務金融學系、人類學系(輔修)',
    exp: [
      'Cobinhood.Ltd Business Development Team Intern',
      'Mu En Art LLC. Part Time Employee',
      'Global Initiatives Symposium,Student Consultant of Marketing Department',
      'NTU ART Festival Minster of Marketing Department',
      'Finance Department Volleyball Team',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/1dc8508f-059e-4298-af10-493b2bbb5399_ps6mw0.jpg',
  },
  {
    _id: '63bab877b1a401c30fc07a02',
    name: 'Charles',
    number: '13',
    jobTitle: 'Savvy Investment Equity Research Analyst',
    exp: [
      'Schroders Investment Management Intern',
      'Shanghai Commercial & Savings Bank Intern',
      '臺灣大學財務金融學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/38a27de1-5071-4634-92d5-5d0a8dde4ff0_v2nlgq.jpg',
  },
  {
    _id: '63bab8f87065749af24d3870',
    name: 'U.C.',
    number: '13',
    jobTitle: 'Mastercard D&S Associate Managing Consultant',
    exp: [
      'APT Business Consultant',
      '臺大假日兒童博物館策展',
      'APT Business Consultant Intern',
      'BCG Case Team Assistant',
      'National Champion, J.P. Morgan Asset Mgmt. Challenge',
      'QIC Research Assistant',
      '元大期貨自營交易實習生',
      '臺大劍道校隊',
      'TutorABC Teacher',
      '臺灣大學財務金融學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/219016_198103.jpeg',
  },
  {
    _id: '63bab98a160a8ac4f8ca86af',
    name: 'Jimmy',
    number: '13',
    jobTitle: 'Terumo Tokyo HQ, product manager',
    exp: [
      'Hilti Market Research Intern',
      'IBM Summer Intern',
      'H.Specctrum Intern',
      "Exchange in Queen's University, Canada",
      '台大社會創新社副社長',
      '2017 聯合國氣候變遷峰會觀察員 (COP 23)',
      '臺灣大學國際企業學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/ac1a2217-bf2d-484a-a342-6d716904649f_fvjz96.jpg',
  },
  {
    _id: '63bab9ee6e9c8d7a8dd3a5fc',
    name: 'Corliss',
    number: '13',
    jobTitle: 'P&G Senior Brand Manager',
    exp: [
      'HEINEKEN Malaysia Berhad Marketing Executive',
      'National Champion, 2017 Unilever Business Competition',
      'Unilever Customer Marketing Intern',
      'LVMH Watch & Jewelry Marketing Executive',
      "Talee's & Starplace Department Store Marketing Project Specialist",
      'CEMS Master in International Management at HEC Paris & Hong Kong University of Science and Technology',
      '臺灣大學國際企業學研究所',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/fd1b6b38-4421-4189-aef4-b301214ea4d2_psjuud.jpg',
  },
  {
    _id: '63baba200af0127fce8dcfc2',
    name: 'Amber',
    number: '13',
    jobTitle: 'Mazars Consulting (Taiwan) Associate Consultant',
    exp: [
      'Athena Capital Management Equity Research Intern',
      'Galderma Sales & Marketing Intern',
      'Salk Institute Undergraduate Researcher',
      'Academia Sinica Summer Research Intern',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/3dbd7192-b119-4cf9-9984-9143ff66f1f2_scekqo.jpg',
  },
  {
    _id: '63bac12100e5313cf83a3133',
    name: 'Anna',
    number: '14',
    jobTitle: 'Standard Foods Corporation, Assistant Product Manager',
    exp: [
      'HOLA, Management Associate',
      'Teach For Taiwan, Project Intern',
      'Hahow, BD & Project Planning Intern',
      'Exchange in University of Pittsburgh',
      'NTU Design Thinking Club',
      '臺灣大學國際企業學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/IMG_4293_m8vxij.jpg',
  },
  {
    _id: '63bac168e2fd01369e22cc9f',
    name: 'Christina',
    number: '14',
    jobTitle: 'IBM, Industry Consultant',
    exp: [
      'PwC, Senior Consultant',
      'Fortuna Intelligence Co., Ltd Marketing Intern',
      'Business Weekly Journalism Intern',
      'Deloitte Risk Advisory Services Intern',
      'Exchange in EMLYON Business School, France',
      '臺灣大學會計學系、財務金融學系(雙主修)',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/IMG_3924_kfkbtl.jpg',
  },
  {
    _id: '63bac1a95e2afdee6529b5cf',
    name: 'Joseph',
    number: '14',
    jobTitle: 'UCLA, PhD in Materials Science & Engineering',
    exp: [
      'Cornell University, MS in Materials Science & Engineering',
      'TSMC R&D Engineer Intern',
      'Deloitte Consultant Intern',
      'MIT Visiting Student Researcher',
      '臺大吉他社社長',
      '臺灣大學材料科學暨工程學系、化學系(輔修)',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/IMG_3925_a5viba.jpg',
  },
  {
    _id: '63bac1f495fba1de7fa96307',
    name: 'Ray',
    number: '14',
    jobTitle: '統一企業 Product Manager',
    exp: ['臺灣大學食品科技研究所碩士', '臺灣大學農業化學系'],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/LRM_EXPORT_21642641529444_20181023_220236383_bbvhwh.jpg',
  },
  {
    _id: '63bac22233bf5835a76cf546',
    name: 'Triny',
    number: '14',
    jobTitle: 'McKinsey & Co, Business Analyst',
    exp: [
      'Mastercard Data & Services (APT) Summer Intern',
      'Standard Chartered Bank, IG Intern',
      'Cathay Life Insurance Company, District Director Assistant',
      '臺灣大學財務金融學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/520492_717836.jpeg',
  },
  {
    _id: '63bac2aa54828a56e70e9607',
    name: 'Jonas',
    number: '15',
    jobTitle: '臺灣大學政治學系',
    exp: [
      'Associate Product Manager, Dcard',
      'Design Thinking Coach, Alphateam',
      'Product Manager, VeryBuy非常勸敗',
      'Rethink Competition 2018 Coach',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/685778_206052.jpeg',
  },
  {
    _id: '63bac2dd0e516b5113457b0e',
    name: 'Leona',
    number: '15',
    jobTitle: 'Shopee Summer Intern',
    exp: [
      'Customer Experience Intern, Shopee',
      'Critical Thinking & Problem Solving (CTPS) Teaching Assistant',
      '臺灣大學政治學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/887745_28336.jpeg',
  },
  {
    _id: '63bac3c08a46c1088074c3e9',
    name: 'Daniel',
    number: '15',
    jobTitle: 'Dell Strategic Business Development Analyst',
    exp: [
      'McKinsey & Co. Scholar',
      'YCP Solidiance Business Analyst Intern',
      'GIS Taiwan Director of Marketing and Design',
      '臺灣大學國際企業學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/710111_168004.jpeg',
  },
  {
    _id: '63bac402f3d2c7f871205b96',
    name: 'Nady',
    number: '15',
    jobTitle: 'MediaTek Engineer',
    exp: [
      'Delta Electronic Electronic Enigeering Intern',
      'NCKU Graduates Association President',
      'NCKU Student Union Public relation team leader',
      '臺灣大學電子所碩士',
      '成功大學資訊工程學系學士',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/294014_242859.jpeg',
  },
  {
    _id: '63bac42f938b1b2f8c8bfd7c',
    name: 'Jason',
    number: '15',
    jobTitle: '臺灣大學心理學系',
    exp: ['臺灣大學心理學系學士', '心理學系系刊《逆光》專案部長'],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/877464_98063.jpeg',
  },
  {
    _id: '63bac4917d4aaaf404ae798c',
    name: 'Nissen',
    number: '16',
    jobTitle: '臺灣大學哲學系',
    exp: [
      'Junyi Academy Software Engineer',
      'Teach for Taiwan Software Engineer',
      'AlphaCamp Teaching Assistant',
      '《臺大人職場手冊》總編輯',
      '臺大哲學桂冠獎 首獎',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/938890_878400.png',
  },
  {
    _id: '63bac4c1af4dede4c363840c',
    name: 'Zora',
    number: '16',
    jobTitle: 'Bytedance Business Analyst',
    exp: [
      'Shopee Business Analyst Intern',
      'Verizon Media (Yahoo) B2C Marketing Intern',
      '只要有人社群顧問 Social Marketing Intern',
      '臺灣大學工商管理學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/580572_378583.png',
  },
  {
    _id: '63bac4f87e395990d7662df0',
    name: 'Jane',
    number: '16',
    jobTitle: '臺灣大學財務金融學系',
    exp: [
      'MagiCapital Private Equity Intern',
      'Shin Kong Investment Trust, Global Investment Intern',
      'beBit Consulting Intern',
      'Calls over Ridges Intern',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/156019_492038.png',
  },
  {
    _id: '63bac54e0f734f0caaef448f',
    name: 'Jeffery',
    number: '16',
    jobTitle: '臺灣大學應數所碩士',
    exp: [
      'Asia Market Access, Market Research Intern',
      '2nd Price, SAS Data Analysis Competition (EVA Airline)',
      'Cathay Life Insurance, Fintech Research Intern',
      '臺大數學系籃隊長',
      '臺灣大學數學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/931806_795715.png',
  },
  {
    _id: '63bac58e84b7c7c5d9ea4cd2',
    name: 'Jean',
    number: '16',
    jobTitle: '臺灣大學心理所碩士',
    exp: [
      'XROUND Digital Marketing Intern',
      'OpenHCI 2019 UX Designer',
      '台北榮民總醫院 臨床實習心理師',
      '台灣積體電路股份有限公司 HR Intern',
      '臺灣大學心理學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/567746_585605.png',
  },
  {
    _id: '63bac621c7d51ba671658188',
    name: 'Fen',
    number: '17',
    jobTitle: 'Cherubic Ventures Analyst',
    exp: [
      'McKinsey & Co.',
      'R&I Intern',
      'Shopee Commercial Summer Intern',
      'AppWorks Intern',
      '臺灣大學商學研究所碩士',
      '政治大學國貿系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/793689_937333.png',
  },
  {
    _id: '63bac651624f6a66b035fff2',
    name: 'Chris',
    number: '17',
    jobTitle: 'McKinsey & Co. DtV Lab ML Solution Intern',
    exp: [
      'AU Optronic Data Science Intern',
      'YEF Program 2018 Delegate',
      '臺灣大學工業工程研究所碩士',
      '交通大學工業工程與管理學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/524421_534246.png',
  },
  {
    _id: '63bac6ce2a078834ed9900c5',
    name: 'James',
    number: '17',
    jobTitle: 'Corning Sr. Strategy Analyst',
    exp: [
      'ADKSH, Business Development Intern',
      'Strategy Consulting—Approach and Practice (SCAP), Teaching Assistant',
      'beBit, Consultant PTA',
      'Appworks Analyst Intern',
      '臺灣大學商學研究所',
      '清華大學經濟學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/72518_954255.png',
  },
  {
    _id: '63bac6fcdedbb643ca4e8e23',
    name: 'Tim',
    number: '17',
    jobTitle: 'Shopee Customer Experience Associate',
    exp: [
      'DIT Startup, BA Intern',
      'ECFIT BD Intern',
      'iFit Supply Chain Intern',
      '臺灣大學國際企業學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/138545_958899.png',
  },
  {
    _id: '63bac73604b9ed5e11682365',
    name: 'Adam',
    number: '17',
    jobTitle: 'Nan Shan Life Management Associate',
    exp: [
      'Shopee Data Analyst intern',
      'Verite Consulting',
      'International, Intern',
      '天下教育，共同創辦人',
      '臺灣大學商學研究所',
      '中原大學企管系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/872041_782218.png',
  },
  {
    _id: '63bac77bad7020fc4f6db4b3',
    name: 'Aidan',
    number: '17',
    jobTitle: '臺灣大學資管學系暨歐盟研究學程',
    exp: [
      'GoShare Product Manager Intern',
      'Microsoft Technical Assistant Intern (Services Team)',
      'Cathay Life Insurance Fintech Engineer Intern',
      'Ernst & Young Management Consultant Intern',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/441912_89654.png',
  },
  {
    _id: '63bac83aad9580e571f3c767',
    name: 'Ethen​',
    number: '18',
    jobTitle: '臺灣大學臨床藥學士',
    exp: [
      'H.Spectrum Accelerator Intern',
      'TTY Biopharm Company Limited Intern',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/780741_12973.jpeg',
  },
  {
    _id: '63bac8812fa0c484856f863d',
    name: 'Leo',
    number: '18',
    jobTitle: 'beBit TECH, Digital Strategy Manager',
    exp: [
      'beBit Consultant',
      'Cathay Financial Holdings, Tech driven team',
      'Nice Clinic Contract-based consultant',
      'COBINHOOD, Operation intern',
      'Exchange in Uppsala University, Sweden',
      '臺灣大學財務金融學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/951243_862080.jpeg',
  },
  {
    _id: '63bac8c80ffb0d6ac4a9533e',
    name: 'Claire',
    number: '18',
    jobTitle: 'Master in Financial Analysis London Business School',
    exp: [
      'Alliance Bernstein Multi Asset Product Analyst Intern',
      'Citibank Global Consumer Banking Summer Analyst',
      'YCP Solidiance Business Consulting Intern',
      'The University of Hong Kong Exchange Student',
      'University of California, Berkeley Exchange Student',
      '臺灣大學經濟學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/479139_587410.jpeg',
  },
  {
    _id: '63bac90458d2a39238593e5f',
    name: 'Trevor',
    number: '18',
    jobTitle: '臺灣大學藝術史研究所',
    exp: [
      'Private Museum Collection Researcher',
      'Institute for Information Industry－MIC Research Assistant',
      'KKday SEA Digital Marketing Intern',
      'NTPC Yingge Ceramics Museum',
      'Special Exhibition Curating Member',
      '臺灣大學國際企業學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/634574_430738.png',
  },
  {
    _id: '63bac9382de9274e1ed33bf9',
    name: 'Sabrina',
    number: '18',
    jobTitle: 'REnato lab Junior Project Coordinator',
    exp: ['台灣大學哲學系'],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/613709_832657.jpeg',
  },
  {
    _id: '63bac96c6b0995c9109c5dc2',
    name: 'ShanYu',
    number: '19',
    jobTitle: 'WOO Network, Product Manager',
    exp: [
      'beBit, Business Consultant PTA',
      'NEXT BANK, User Experience Researcher intern',
      'Visiting student at Faculty of Humanities at Charles University',
      '臺灣大學心理學系雙社會學系暨婦女與性別研究學程',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/613709_832657.jpeg',
  },
  {
    _id: '63bac99a272cce01b71bd650',
    name: 'Shannon',
    number: '19',
    jobTitle: "L'Oréal, HR Management Trainee",
    exp: [
      'Mercer Taiwan, Career Business Intern',
      'Rayark Game, Intern',
      'Design Thinking Coach',
      'Freelance Illustrator',
      '台灣大學心理學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/363851_789439.png',
  },
  {
    _id: '63bac9ca031f2f166817c43e',
    name: 'Laura',
    number: '19',
    jobTitle: '臺灣大學會計學系',
    exp: [
      'Garena, Management Associate',
      'beBit, Business Consultant PTA',
      'Standard Chartered Bank, International Graduate Intern-Digital Banking',
      'Deloitte, Audit & Assurance Intern',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/930816_628434.jpeg',
  },
  {
    _id: '63bac9fb2e6dd0cfb62ef3fc',
    name: 'Eric',
    number: '19',
    jobTitle: 'Insider Business Development Specialist',
    exp: [
      'Shopee, Category Management Intern',
      'JihSun Bank, Treasury Division Intern',
      '180 Degree Consulting Club Taiwan, Director of Business Development',
      '臺灣大學財務金融學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/253608_403862.jpeg',
  },
  {
    _id: '63baca2af52eee7d699aa314',
    name: 'Nora',
    number: '19',
    jobTitle: '臺灣大學流預所',
    exp: [
      'Taiwan Burden of Disease Center, Research Assistant',
      '心理學系系刊《逆光》專案部長',
      '臺灣大學心理學系、生物統計學程',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/284054_827854.png',
  },
  {
    _id: '63baca51a203c74a7798209b',
    name: 'Vera',
    number: '19',
    jobTitle: '臺灣大學財務金融學系',
    exp: [
      'ActiveFence, Product Management Intern Research Assistant',
      'beBit, Business Consultant PTA',
      'Taishin Investment Advisory, Analyst Intern',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/354585_576646.png',
  },
  {
    _id: '63bacd744442774554d6249e',
    name: 'Chris',
    number: '20',
    jobTitle: 'Analyst Intern at CloudAlpha Capital',
    exp: [
      'AMagiCapital Private Equity Analyst Intern',
      'Statement Dog Equity Research Intern',
      'Affairs of Economic of R.O.C Intern',
      'RYS-200 Yoga Instructor NTU & NTNU Literature Awards',
      '臺灣大學哲學系、經濟系（輔修）',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/656371_484756.png',
  },
  {
    _id: '63bacd9afcb3a36ce0102753',
    name: 'Paul',
    number: '20',
    jobTitle: 'Ambrose, Advisors Analyst',
    exp: ['Exchange in Lund University', '臺灣大學財務金融學系'],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/561963_72674.png',
  },
  {
    _id: '63bacdc929693c5ecb0bda9b',
    name: 'Sara',
    number: '20',
    jobTitle: '臺灣大學商學研究所',
    exp: [
      'EFubon Financial Holdings Product Development Intern',
      'DBS Bank Credit Analyst',
      'Eastspring Investments Fund Accounting Intern',
      'Ernst & Young Audit Intern',
      '臺灣大學會計學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/871631_242869.png',
  },
  {
    _id: '63bace0e58edb2cb1f652ed1',
    name: 'Hannibal',
    number: '20',
    jobTitle: '臺灣大學機械工程學系',
    exp: [
      'EmoMask Technology Co-Founder & CEO',
      'Google Hardware Product Sprint Program Student Team Leader',
      'National Taiwan University Racing Team Embedded System Engineer',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/169119_306379.png',
  },
  {
    _id: '63bace42ab3f759759705391',
    name: 'Louis',
    number: '20',
    jobTitle: 'Statementdog Academy, Business Development Manager',
    exp: [
      'Tang Wealth (Beijing, China) Research Assistant Intern',
      'Cathay United Bank, Digital Application Intern',
      'Exchange in Guanghua School of Management Peking University, China',
      '臺大魔術社社長',
      '臺灣大學財務金融學系、心理學系（雙主修）',
    ],
    tags: ['測試用', '測試用'],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/714699_548083.jpeg',
  },
  {
    _id: '63bace6a650930156604646d',
    name: 'Amanda',
    number: '20',
    jobTitle: 'Mercer Consulting Career Business Intern',
    exp: ['臺灣大學社會學研究所', '臺灣大學社會學系'],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/67001_578106.jpeg',
  },
  {
    _id: '63baceba3c5c82a70c81e79d',
    name: 'Emily',
    number: '21',
    jobTitle: '臺灣大學財務金融所',
    exp: [
      'WOO Network Product Management Intern',
      'Cathay United Bank International Strategic Planning Intern',
      'Deloitte & Touche Financial Industry Risk Consultant Intern',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/493187_618519.jpeg',
  },
  {
    _id: '63bacf1d204aee925a6498f7',
    name: 'Gary',
    number: '21',
    jobTitle: 'Hotai Motor Lexus Intern',
    exp: [
      'FunNow Growth Intern',
      'Standard Chartered Bank Summer Intern',
      'CTPS Teaching Assistant',
      '臺灣大學國際企業學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/571210_236591.jpeg',
  },
  {
    _id: '63bacf4aca9469a2b3d1dc0f',
    name: 'Iris',
    number: '21',
    jobTitle: 'Unilever Marketing Intern',
    exp: [
      'Cathay SITE Summer Intern',
      'Exchange in Yale-NUS, Singapore',
      '臺灣大學國際企業學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/400377_14373.jpeg',
  },
  {
    _id: '63bacf88637993f9bc951557',
    name: 'Jenny',
    number: '21',
    jobTitle: '臺灣大學國際企業學系',
    exp: [
      'Appier Enterprise Solution Sales Intern',
      '25sprout Business Development Intern',
      '臺灣大學國際企業學系',
    ],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/289545_238536.jpeg',
  },
  {
    _id: '63bacfa807085c47888560a1',
    name: 'Jim',
    number: '21',
    jobTitle: 'Graphen Data Scientist Intern',
    exp: ['臺灣大學資訊工程學系'],
    tags: [''],
    avater:
      'https://custom-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_960,w_480,f_auto,q_auto/89241/385535_892520.jpeg',
  },
];
